export type Locale = "en" | "fr";
const en = {
  lang: "en", other: { label: "Français", href: "/fr/" },
  meta: { title: "The Value Office — Cohort 0 | High-Value Relationship & Market Access Operating System", description: "A selective 3-month execution environment for 10 Tunisian founders, CEOs and experts building authority, high-value relationships and commercial opportunities through LinkedIn." },
  cta: "REQUEST AN INVITATION", cta2: "SEE THE SYSTEM",
  hero: { label: "COHORT 0", cat: "HIGH-VALUE RELATIONSHIP & MARKET ACCESS OPERATING SYSTEM", h1: "You have already spent years becoming valuable.", sub: "Now build the system that makes that value visible, trusted and connected to opportunity.", body: "A high-touch 3-month execution environment for 10 Tunisian founders, CEOs and experts who are ready to turn accumulated expertise, reputation and knowledge into visibility, relationships, opportunities and eventually commercial value.", note: "Invite-only. Recommendation-based." },
  inbound: { title: "Get your positioning right, and the market starts writing to you.", sub: "Real invitations and messages received inbound by Mohamed Amine Khiari from international professionals. This is what a clear category looks like.", dm: "Direct message", invite: "Invitations with notes", note: "Unsolicited inbound, shown as evidence of positioning. Not client relationships, and not endorsements of Cohort 0." },
  gap: "You may already have the value. The market may not see all of it.",
  outcomesTitle: "What changes when the market can see your value.",
  outcomes: [["Wealth", "More valuable conversations, more opportunity, more leverage and freedom."], ["Relationships", "A network that compounds, and a community built on shared values and problems."], ["Status", "A public identity that matches the level you have actually earned."], ["Legacy", "Years of experience turned into intellectual and market assets."]],
  productTitle: "LinkedIn is the infrastructure. It is not the product.",
  valueFlow: ["Experience", "Knowledge", "Positioning", "Authority", "Visibility", "Relationships", "Opportunities", "Commercial value"],
  miningTitle: "Before we teach you what to publish, we study you.",
  mining: ["History", "Execution and projects", "Successes and failures", "Lessons and mistakes", "Relationships and brands", "Turning points and ambitions"],
  miningQuote: "We don’t manufacture authority. We extract, architect and activate the authority you have already earned.",
  dnaTitle: "Your Personal Brand DNA, in your own voice.",
  dna: ["Positioning", "Proof", "Point of view", "Expertise", "Stories", "Voice", "Signature"],
  armadaTitle: "You stop starting from zero every Monday.",
  armada: ["A story", "A lesson", "A point of view", "A framework", "A case study", "A conversation"],
  armadaLine: "One real experience, many assets. Content Armada™.",
  stagesTitle: "One operating system, six stages.",
  stages: [["Position", "Make your value clear and legible."], ["Connect", "Find the right people."], ["Communicate", "Make your expertise visible and credible."], ["Converse", "Turn connections into meaningful relationships."], ["Convert", "Turn relevant relationships into qualified commercial opportunities."], ["Compound", "Turn proof, relationships and results into an asset that keeps growing."]],
  pipelineTitle: "A repeatable mechanism for high-value relationships.",
  pipeline: ["Target", "Connect", "Engage", "Converse", "Qualify", "Opportunity", "Deal"],
  execTitle: "You don’t pass because you watched the lesson. You move forward because you executed it.",
  sat: ["Every Saturday", "17:00 to 18:00: Masterclass", "18:00 to 19:00: Workshop"], loopLabel: "The weekly loop",
  loop: ["Learn", "Build", "Execute", "Measure", "Review", "Pass or rework"],
  execQuote: "A task without a deadline is a wish. A metric without a target is only data.",
  networkTitle: "The network behind the system.",
  networkLine: "A network of founders, executives and investors, built through deliberate relationship-building. The point is not who you can name-drop. It is learning to build meaningful relationships at a higher level.",
  networkNote: "Screenshots of Mohamed Amine Khiari’s own first-degree LinkedIn connections. They show his relationship-building track record and do not imply endorsement of Cohort 0, client relationships or introductions.",
  founderTitle: "Built by someone who has done this at scale.", founderRole: "Founder, The Value Office",
  stats: [["15+", "years across entrepreneurship, finance, advisory, venture capital and international ecosystems"], ["5+", "years inside Silicon Valley"], ["34K+", "LinkedIn followers"], ["348K+", "people connected across international communities and platforms"], ["14+", "countries across 4 continents"]],
  forTitle: "Who this is for", notTitle: "Who this is not for",
  forYou: ["You have real expertise or a track record, and the market sees only part of it.", "You want better conversations with clients, partners and decision-makers, not more noise.", "You will execute every week and bring the evidence back.", "You prefer a few serious peers to a large anonymous crowd."],
  notYou: ["You want followers, virality or influencer status.", "You are looking for shortcuts or a guaranteed result.", "You want recorded lessons to watch at your own pace.", "You expect introductions to specific people."],
  cohortTitle: "Cohort 0.", start: "Start",
  cohort: [["10", "Tunisian founders, CEOs and experts"], ["3 months", "of weekly, execution-led work"], ["Invite-only", "every seat is considered individually"], ["Recommendation-based", "the room is built through trust"]],
  faqTitle: "Questions",
  faq: [
    ["What exactly is The Value Office?", "A selective operating system that helps experienced professionals turn accumulated expertise, reputation and knowledge into visibility, relationships and commercial opportunities. LinkedIn is the infrastructure, not the product."],
    ["Is this about getting followers?", "No. Followers, impressions and engagement are supporting indicators. The system runs from vision and positioning to authority, network, relationships and opportunities."],
    ["What do you do before telling me what to publish?", "We study you first. We build a private Knowledge Base from your history, projects, successes, failures, lessons and relationships. We extract your Personal Brand DNA (positioning, proof, point of view, expertise, stories, values, voice, signature) and a Voiceprint. The goal is to make you sound more like yourself, not like us."],
    ["What is Content Armada™?", "Your own history becomes the raw material. One real experience can become a story, a lesson, a point of view, a framework, a case study and a conversation. You stop starting from zero every Monday."],
    ["Will I be introduced to specific people?", "No. We teach a repeatable mechanism to identify, approach, engage and develop relationships with high-value people relevant to your market. You build your own network."],
    ["What does the weekly format look like?", "Every Saturday: masterclass 17:00 to 18:00, workshop 18:00 to 19:00. Each week has an objective, deliverables, deadlines, metrics, evidence and a review, plus clinics. You bring your work back every week."],
    ["What results can I expect?", "We promise a mechanism and an environment, not outcomes we cannot control. We do not guarantee clients, investors, introductions or revenue."],
    ["How does selection work?", "Cohort 0 is invite-only and recommendation-based, with 10 places. Every application is reviewed individually, and terms are shared after selection."],
  ],
  close: ["Your experience is an asset. Your knowledge is an asset. Your reputation, your relationships and your stories are assets.", "The question is whether all of them are working together. The Value Office helps you architect the system that connects them."],
  closeH: "Turn accumulated value into market value.", closeNote: "Invite-only. Recommendation-based. Applications are reviewed individually.",
};
const fr: typeof en = {
  lang: "fr", other: { label: "English", href: "/" },
  meta: { title: "The Value Office — Cohorte 0 | Système d’exploitation des relations de haute valeur et de l’accès au marché", description: "Un environnement d’exécution sélectif de 3 mois pour 10 fondateurs, dirigeants et experts tunisiens qui construisent autorité, relations de haute valeur et opportunités commerciales grâce à LinkedIn." },
  cta: "DEMANDER UNE INVITATION", cta2: "VOIR LE SYSTÈME",
  hero: { label: "COHORTE 0", cat: "SYSTÈME D’EXPLOITATION DES RELATIONS DE HAUTE VALEUR ET DE L’ACCÈS AU MARCHÉ", h1: "Vous avez déjà passé des années à construire votre valeur.", sub: "Construisez maintenant le système qui la rend visible, crédible et reliée aux opportunités.", body: "Un environnement d’exécution intensif de 3 mois, en petit comité, pour 10 fondateurs, dirigeants et experts tunisiens prêts à transformer leur expertise, leur réputation et leurs connaissances accumulées en visibilité, relations, opportunités et, à terme, valeur commerciale.", note: "Sur invitation uniquement. Sur recommandation." },
  inbound: { title: "Quand votre positionnement est clair, le marché vient à vous.", sub: "Des invitations et messages réels reçus en inbound par Mohamed Amine Khiari de la part de professionnels internationaux. Voilà à quoi ressemble une catégorie claire.", dm: "Message direct", invite: "Invitations avec notes", note: "Inbound spontané, présenté comme preuve de positionnement. Il ne s’agit ni de relations clients, ni de recommandations de la Cohorte 0." },
  gap: "Vous avez peut-être déjà la valeur. Le marché n’en voit peut-être qu’une partie.",
  outcomesTitle: "Ce qui change quand le marché voit votre valeur.",
  outcomes: [["Richesse", "Des conversations de plus grande valeur, plus d’opportunités, plus de levier et de liberté."], ["Relations", "Un réseau qui se capitalise et une communauté fondée sur des valeurs et des problèmes partagés."], ["Statut", "Une identité publique à la hauteur du niveau que vous avez réellement atteint."], ["Héritage", "Des années d’expérience transformées en actifs intellectuels et de marché."]],
  productTitle: "LinkedIn est l’infrastructure. Ce n’est pas le produit.",
  valueFlow: ["Expérience", "Connaissance", "Positionnement", "Autorité", "Visibilité", "Relations", "Opportunités", "Valeur commerciale"],
  miningTitle: "Avant de vous dire quoi publier, nous vous étudions.",
  mining: ["Parcours", "Exécution et projets", "Réussites et échecs", "Leçons et erreurs", "Relations et marques", "Tournants et ambitions"],
  miningQuote: "Nous ne fabriquons pas l’autorité. Nous extrayons, architecturons et activons celle que vous avez déjà méritée.",
  dnaTitle: "Votre ADN de marque personnelle, avec votre propre voix.",
  dna: ["Positionnement", "Preuves", "Point de vue", "Expertise", "Récits", "Voix", "Signature"],
  armadaTitle: "Fini de repartir de zéro chaque lundi.",
  armada: ["Un récit", "Une leçon", "Un point de vue", "Un cadre", "Une étude de cas", "Une conversation"],
  armadaLine: "Une expérience réelle, de nombreux actifs. Content Armada™.",
  stagesTitle: "Un système d’exploitation, six étapes.",
  stages: [["Positionner", "Rendre votre valeur claire et lisible."], ["Connecter", "Trouver les bonnes personnes."], ["Communiquer", "Rendre votre expertise visible et crédible."], ["Dialoguer", "Transformer des contacts en relations qui comptent."], ["Convertir", "Transformer des relations pertinentes en opportunités commerciales qualifiées."], ["Capitaliser", "Faire de vos preuves, relations et résultats un actif qui grandit."]],
  pipelineTitle: "Un mécanisme reproductible pour les relations de haute valeur.",
  pipeline: ["Cibler", "Connecter", "Engager", "Dialoguer", "Qualifier", "Opportunité", "Affaire"],
  execTitle: "Vous ne validez pas parce que vous avez regardé la leçon. Vous avancez parce que vous l’avez exécutée.",
  sat: ["Chaque samedi", "17h00 à 18h00 : Masterclass", "18h00 à 19h00 : Atelier"], loopLabel: "La boucle hebdomadaire",
  loop: ["Apprendre", "Construire", "Exécuter", "Mesurer", "Revoir", "Valider ou reprendre"],
  execQuote: "Une tâche sans échéance est un souhait. Une mesure sans cible n’est qu’une donnée.",
  networkTitle: "Le réseau derrière le système.",
  networkLine: "Un réseau de fondateurs, dirigeants et investisseurs, construit par une démarche relationnelle délibérée. L’enjeu n’est pas de citer des noms, mais d’apprendre à bâtir des relations professionnelles de plus haut niveau.",
  networkNote: "Captures des relations LinkedIn de premier niveau de Mohamed Amine Khiari. Elles illustrent sa pratique relationnelle et n’impliquent ni recommandation de la Cohorte 0, ni relation client, ni introduction.",
  founderTitle: "Conçu par quelqu’un qui l’a fait à grande échelle.", founderRole: "Fondateur, The Value Office",
  stats: [["15+", "ans en entrepreneuriat, finance, conseil, capital-risque et écosystèmes internationaux"], ["5+", "ans au cœur de la Silicon Valley"], ["34K+", "abonnés LinkedIn"], ["348K+", "personnes connectées via des communautés et plateformes internationales"], ["14+", "pays sur 4 continents"]],
  forTitle: "Pour qui", notTitle: "Pour qui ce n’est pas",
  forYou: ["Vous avez une vraie expertise ou un parcours, et le marché n’en voit qu’une partie.", "Vous voulez de meilleures conversations avec clients, partenaires et décideurs, pas plus de bruit.", "Vous exécuterez chaque semaine et rapporterez les preuves.", "Vous préférez quelques pairs sérieux à une foule anonyme."],
  notYou: ["Vous voulez des abonnés, de la viralité ou un statut d’influenceur.", "Vous cherchez des raccourcis ou un résultat garanti.", "Vous voulez des leçons enregistrées à suivre à votre rythme.", "Vous attendez des introductions à des personnes précises."],
  cohortTitle: "Cohorte 0.", start: "Début",
  cohort: [["10", "fondateurs, dirigeants et experts tunisiens"], ["3 mois", "de travail hebdomadaire axé sur l’exécution"], ["Sur invitation", "chaque place est étudiée individuellement"], ["Sur recommandation", "le groupe se construit sur la confiance"]],
  faqTitle: "Questions",
  faq: [
    ["Qu’est-ce que The Value Office, concrètement ?", "Un système d’exploitation sélectif qui aide des professionnels expérimentés à transformer leur expertise, leur réputation et leurs connaissances accumulées en visibilité, relations et opportunités commerciales. LinkedIn est l’infrastructure, pas le produit."],
    ["S’agit-il de gagner des abonnés ?", "Non. Abonnés, impressions et engagement sont des indicateurs secondaires. Le système va de la vision et du positionnement à l’autorité, au réseau, aux relations et aux opportunités."],
    ["Que faites-vous avant de me dire quoi publier ?", "Nous commençons par vous étudier. Nous construisons une base de connaissances privée à partir de votre parcours, projets, réussites, échecs, leçons et relations. Nous en extrayons votre ADN de marque personnelle (positionnement, preuves, point de vue, expertise, récits, valeurs, voix, signature) et une empreinte vocale. L’objectif : que vous ressembliez davantage à vous-même, pas à nous."],
    ["Qu’est-ce que Content Armada™ ?", "Votre propre histoire devient la matière première. Une expérience réelle peut devenir un récit, une leçon, un point de vue, un cadre, une étude de cas et une conversation. Vous ne repartez plus de zéro chaque lundi."],
    ["Serai-je introduit auprès de personnes précises ?", "Non. Nous enseignons un mécanisme reproductible pour identifier, approcher, engager et développer des relations avec des personnes de haute valeur pertinentes pour votre marché. Vous construisez votre propre réseau."],
    ["À quoi ressemble le format hebdomadaire ?", "Chaque samedi : masterclass de 17h00 à 18h00, atelier de 18h00 à 19h00. Chaque semaine comporte un objectif, des livrables, des échéances, des mesures, des preuves et une revue, ainsi que des cliniques. Vous rapportez votre travail chaque semaine."],
    ["Quels résultats puis-je attendre ?", "Nous promettons un mécanisme et un environnement, pas des résultats que nous ne maîtrisons pas. Nous ne garantissons ni clients, ni investisseurs, ni introductions, ni chiffre d’affaires."],
    ["Comment se fait la sélection ?", "La Cohorte 0 est sur invitation et sur recommandation, avec 10 places. Chaque candidature est étudiée individuellement et les conditions sont communiquées après la sélection."],
  ],
  close: ["Votre expérience est un actif. Vos connaissances sont un actif. Votre réputation, vos relations et vos histoires sont des actifs.", "La question est de savoir si tous travaillent ensemble. The Value Office vous aide à architecturer le système qui les relie."],
  closeH: "Transformez la valeur accumulée en valeur de marché.", closeNote: "Sur invitation uniquement. Sur recommandation. Chaque candidature est étudiée individuellement.",
};
export const T: Record<Locale, typeof en> = { en, fr };
